// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(TecnoMovilDbContext))]
    [Migration("20260303092537_AddAnalisisIA")]
    partial class AddAnalisisIA
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("backend.Models.AnalisisIA", b =>
                {
                    b.Property<int>("IdAnalisis")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_analisis");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAnalisis"));

                    b.Property<DateTime>("FechaGeneracion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_generacion");

                    b.Property<DateTime>("PeriodoFin")
                        .HasColumnType("datetime2")
                        .HasColumnName("periodo_fin");

                    b.Property<DateTime>("PeriodoInicio")
                        .HasColumnType("datetime2")
                        .HasColumnName("periodo_inicio");

                    b.Property<int?>("TokensUsados")
                        .HasColumnType("int")
                        .HasColumnName("tokens_usados");

                    b.Property<int>("TotalProductosAnalizados")
                        .HasColumnType("int")
                        .HasColumnName("total_productos_analizados");

                    b.HasKey("IdAnalisis");

                    b.ToTable("Analisis_IA");
                });

            modelBuilder.Entity("backend.Models.Atributo", b =>
                {
                    b.Property<int>("IdAtributo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_atributo");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAtributo"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit")
                        .HasColumnName("activo");

                    b.Property<string>("NombreAtributo")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("nombre_atributo");

                    b.Property<string>("TipoDato")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("tipo_dato");

                    b.Property<string>("Unidad")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("unidad");

                    b.HasKey("IdAtributo");

                    b.HasIndex("NombreAtributo")
                        .IsUnique();

                    b.ToTable("Atributo");
                });

            modelBuilder.Entity("backend.Models.Categoria", b =>
                {
                    b.Property<int>("IdCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_categoria");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCategoria"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit")
                        .HasColumnName("activo");

                    b.Property<string>("NombreCategoria")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nombre_categoria");

                    b.HasKey("IdCategoria");

                    b.ToTable("Categoria");
                });

            modelBuilder.Entity("backend.Models.Cliente", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_cliente");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCliente"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit")
                        .HasColumnName("activo");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("Identificacion")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)")
                        .HasColumnName("identificacion");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombres");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("telefono");

                    b.Property<string>("TipoIdentificacion")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("tipo_identificacion");

                    b.HasKey("IdCliente");

                    b.HasIndex("Identificacion")
                        .IsUnique();

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("backend.Models.Configuracion", b =>
                {
                    b.Property<int>("IdConfig")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_config");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdConfig"));

                    b.Property<decimal>("IvaPorcentaje")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("iva_porcentaje");

                    b.HasKey("IdConfig");

                    b.ToTable("Configuracion", t =>
                        {
                            t.HasCheckConstraint("CK_Configuracion_UnaFila", "id_config = 1");
                        });

                    b.HasData(
                        new
                        {
                            IdConfig = 1,
                            IvaPorcentaje = 15.00m
                        });
                });

            modelBuilder.Entity("backend.Models.DetalleAnalisisIA", b =>
                {
                    b.Property<int>("IdDetalleAnalisis")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_detalle_analisis");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDetalleAnalisis"));

                    b.Property<int>("IdAnalisis")
                        .HasColumnType("int")
                        .HasColumnName("id_analisis");

                    b.Property<int>("IdProducto")
                        .HasColumnType("int")
                        .HasColumnName("id_producto");

                    b.Property<string>("Justificacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("justificacion");

                    b.Property<string>("NivelUrgencia")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("nivel_urgencia");

                    b.Property<int>("ProyeccionProximoMes")
                        .HasColumnType("int")
                        .HasColumnName("proyeccion_proximo_mes");

                    b.Property<int>("SugerenciaCompra")
                        .HasColumnType("int")
                        .HasColumnName("sugerencia_compra");

                    b.Property<string>("VentasHistoricasJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ventas_historicas_json");

                    b.HasKey("IdDetalleAnalisis");

                    b.HasIndex("IdAnalisis");

                    b.HasIndex("IdProducto");

                    b.ToTable("Detalle_Analisis_IA");
                });

            modelBuilder.Entity("backend.Models.DetalleFactura", b =>
                {
                    b.Property<int>("IdDetalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_detalle");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDetalle"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int")
                        .HasColumnName("cantidad");

                    b.Property<string>("DescripcionItem")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("descripcion_item");

                    b.Property<int>("IdFactura")
                        .HasColumnType("int")
                        .HasColumnName("id_factura");

                    b.Property<int?>("IdProducto")
                        .HasColumnType("int")
                        .HasColumnName("id_producto");

                    b.Property<int?>("IdReparacion")
                        .HasColumnType("int")
                        .HasColumnName("id_reparacion");

                    b.Property<int?>("IdSerial")
                        .HasColumnType("int")
                        .HasColumnName("id_serial");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("precio_unitario");

                    b.Property<string>("TipoItem")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("tipo_item");

                    b.HasKey("IdDetalle");

                    b.HasIndex("IdFactura")
                        .HasDatabaseName("IX_Detalle_factura");

                    b.HasIndex("IdProducto");

                    b.HasIndex("IdReparacion");

                    b.HasIndex("IdSerial");

                    b.ToTable("Detalle_Factura", t =>
                        {
                            t.HasTrigger("trg_DetalleFactura_AfterInsert");

                            t.HasTrigger("trg_DetalleFactura_RecalcularTotales");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("backend.Models.Factura", b =>
                {
                    b.Property<int>("IdFactura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_factura");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFactura"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int")
                        .HasColumnName("id_cliente");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    b.Property<decimal>("Iva")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("iva");

                    b.Property<decimal>("IvaPorcentaje")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("iva_porcentaje");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("subtotal");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total");

                    b.HasKey("IdFactura");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Factura", t =>
                        {
                            t.HasTrigger("trg_DetalleFactura_RecalcularTotales")
                                .HasDatabaseName("trg_DetalleFactura_RecalcularTotales1");

                            t.HasTrigger("trg_Factura_SetIVA");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("backend.Models.FacturaReparacion", b =>
                {
                    b.Property<int>("IdFactura")
                        .HasColumnType("int")
                        .HasColumnName("id_factura");

                    b.Property<int>("IdReparacion")
                        .HasColumnType("int")
                        .HasColumnName("id_reparacion");

                    b.HasKey("IdFactura", "IdReparacion");

                    b.HasIndex("IdReparacion")
                        .HasDatabaseName("IX_FR_reparacion");

                    b.ToTable("Factura_Reparacion");
                });

            modelBuilder.Entity("backend.Models.MovimientoInventario", b =>
                {
                    b.Property<int>("IdMovimiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_movimiento");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMovimiento"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int")
                        .HasColumnName("cantidad");

                    b.Property<string>("Detalle")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("detalle");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha");

                    b.Property<int>("IdProducto")
                        .HasColumnType("int")
                        .HasColumnName("id_producto");

                    b.Property<int?>("IdSerial")
                        .HasColumnType("int")
                        .HasColumnName("id_serial");

                    b.Property<int?>("ReferenciaId")
                        .HasColumnType("int")
                        .HasColumnName("referencia_id");

                    b.Property<string>("ReferenciaTabla")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("referencia_tabla");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("tipo");

                    b.HasKey("IdMovimiento");

                    b.HasIndex("IdSerial");

                    b.HasIndex("IdProducto", "Fecha")
                        .HasDatabaseName("IX_MI_producto_fecha");

                    b.ToTable("Movimiento_Inventario", t =>
                        {
                            t.HasTrigger("trg_MI_AfterInsert");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("backend.Models.Producto", b =>
                {
                    b.Property<int>("IdProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_producto");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProducto"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit")
                        .HasColumnName("activo");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("descripcion");

                    b.Property<bool>("EsSerializado")
                        .HasColumnType("bit")
                        .HasColumnName("es_serializado");

                    b.Property<int>("IdCategoria")
                        .HasColumnType("int")
                        .HasColumnName("id_categoria");

                    b.Property<string>("Imagen")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("imagen");

                    b.Property<string>("NombreProducto")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("nombre_producto");

                    b.Property<decimal>("PrecioVenta")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("precio_venta");

                    b.Property<int>("StockActual")
                        .HasColumnType("int")
                        .HasColumnName("stock_actual");

                    b.HasKey("IdProducto");

                    b.HasIndex("IdCategoria")
                        .HasDatabaseName("IX_Producto_id_categoria");

                    b.ToTable("Producto");
                });

            modelBuilder.Entity("backend.Models.ProductoAtributo", b =>
                {
                    b.Property<int>("IdProducto")
                        .HasColumnType("int")
                        .HasColumnName("id_producto");

                    b.Property<int>("IdAtributo")
                        .HasColumnType("int")
                        .HasColumnName("id_atributo");

                    b.Property<bool?>("ValorBool")
                        .HasColumnType("bit")
                        .HasColumnName("valor_bool");

                    b.Property<DateOnly?>("ValorFecha")
                        .HasColumnType("date")
                        .HasColumnName("valor_fecha");

                    b.Property<decimal?>("ValorNumero")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("valor_numero");

                    b.Property<string>("ValorTexto")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("valor_texto");

                    b.HasKey("IdProducto", "IdAtributo");

                    b.HasIndex("IdAtributo", "IdProducto")
                        .HasDatabaseName("IX_PA_Atributo");

                    b.ToTable("Producto_Atributo", t =>
                        {
                            t.HasTrigger("trg_PA_ValidarTipo");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("backend.Models.ProductoSerial", b =>
                {
                    b.Property<int>("IdSerial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_serial");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSerial"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("estado");

                    b.Property<int>("IdProducto")
                        .HasColumnType("int")
                        .HasColumnName("id_producto");

                    b.Property<string>("NumeroSerieImei")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("numero_serie_imei");

                    b.HasKey("IdSerial");

                    b.HasIndex("IdProducto")
                        .HasDatabaseName("IX_Serial_id_producto");

                    b.HasIndex("NumeroSerieImei")
                        .IsUnique();

                    b.ToTable("Producto_Serial");
                });

            modelBuilder.Entity("backend.Models.Reparacion", b =>
                {
                    b.Property<int>("IdReparacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_reparacion");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdReparacion"));

                    b.Property<bool?>("Aprobado")
                        .HasColumnType("bit")
                        .HasColumnName("aprobado");

                    b.Property<decimal>("CostoManoObra")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("costo_mano_obra");

                    b.Property<string>("DescripcionFalla")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("descripcion_falla");

                    b.Property<string>("DiagnosticoFinal")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("diagnostico_final");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("estado");

                    b.Property<DateTime?>("FechaAprobacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_aprobacion");

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_ingreso");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int")
                        .HasColumnName("id_cliente");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    b.Property<string>("ModeloEquipo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("modelo_equipo");

                    b.Property<string>("MotivoRechazo")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("motivo_rechazo");

                    b.Property<string>("SerieImeiIngreso")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("serie_imei_ingreso");

                    b.HasKey("IdReparacion");

                    b.HasIndex("IdCliente")
                        .HasDatabaseName("IX_Reparacion_cliente");

                    b.HasIndex("IdUsuario")
                        .HasDatabaseName("IX_Reparacion_tecnico");

                    b.ToTable("Reparacion");
                });

            modelBuilder.Entity("backend.Models.ReparacionRepuesto", b =>
                {
                    b.Property<int>("IdReparacionRepuesto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_reparacion_repuesto");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdReparacionRepuesto"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int")
                        .HasColumnName("cantidad");

                    b.Property<decimal?>("CostoUnitario")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("costo_unitario");

                    b.Property<int>("IdProducto")
                        .HasColumnType("int")
                        .HasColumnName("id_producto");

                    b.Property<int>("IdReparacion")
                        .HasColumnType("int")
                        .HasColumnName("id_reparacion");

                    b.Property<int?>("IdSerial")
                        .HasColumnType("int")
                        .HasColumnName("id_serial");

                    b.Property<decimal?>("PrecioCobrado")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("precio_cobrado");

                    b.HasKey("IdReparacionRepuesto");

                    b.HasIndex("IdProducto");

                    b.HasIndex("IdSerial");

                    b.HasIndex("IdReparacion", "IdProducto")
                        .IsUnique()
                        .HasDatabaseName("UX_RR_NoSerial")
                        .HasFilter("[id_serial] IS NULL");

                    b.HasIndex("IdReparacion", "IdSerial")
                        .IsUnique()
                        .HasDatabaseName("UX_RR_ConSerial")
                        .HasFilter("[id_serial] IS NOT NULL");

                    b.ToTable("Reparacion_Repuesto", t =>
                        {
                            t.HasTrigger("trg_RR_ValidarSerialProducto");

                            t.HasTrigger("trg_ReparacionRepuesto_AfterInsert");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("backend.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit")
                        .HasColumnName("activo");

                    b.Property<string>("Correo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("correo");

                    b.Property<string>("Identificacion")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)")
                        .HasColumnName("identificacion");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombres");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("rol");

                    b.Property<string>("TipoIdentificacion")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("tipo_identificacion");

                    b.HasKey("IdUsuario");

                    b.HasIndex("Correo")
                        .IsUnique()
                        .HasFilter("[correo] IS NOT NULL");

                    b.HasIndex("Identificacion")
                        .IsUnique();

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("backend.Models.DetalleAnalisisIA", b =>
                {
                    b.HasOne("backend.Models.AnalisisIA", "AnalisisIA")
                        .WithMany("Detalles")
                        .HasForeignKey("IdAnalisis")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AnalisisIA");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("backend.Models.DetalleFactura", b =>
                {
                    b.HasOne("backend.Models.Factura", "Factura")
                        .WithMany("Detalles")
                        .HasForeignKey("IdFactura")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("IdProducto");

                    b.HasOne("backend.Models.Reparacion", "Reparacion")
                        .WithMany()
                        .HasForeignKey("IdReparacion")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("backend.Models.ProductoSerial", "Serial")
                        .WithMany()
                        .HasForeignKey("IdSerial");

                    b.Navigation("Factura");

                    b.Navigation("Producto");

                    b.Navigation("Reparacion");

                    b.Navigation("Serial");
                });

            modelBuilder.Entity("backend.Models.Factura", b =>
                {
                    b.HasOne("backend.Models.Cliente", "Cliente")
                        .WithMany("Facturas")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend.Models.Usuario", "Vendedor")
                        .WithMany("Facturas")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Vendedor");
                });

            modelBuilder.Entity("backend.Models.FacturaReparacion", b =>
                {
                    b.HasOne("backend.Models.Factura", "Factura")
                        .WithMany("FacturaReparaciones")
                        .HasForeignKey("IdFactura")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend.Models.Reparacion", "Reparacion")
                        .WithMany("FacturaReparaciones")
                        .HasForeignKey("IdReparacion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Factura");

                    b.Navigation("Reparacion");
                });

            modelBuilder.Entity("backend.Models.MovimientoInventario", b =>
                {
                    b.HasOne("backend.Models.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.ProductoSerial", "Serial")
                        .WithMany()
                        .HasForeignKey("IdSerial");

                    b.Navigation("Producto");

                    b.Navigation("Serial");
                });

            modelBuilder.Entity("backend.Models.Producto", b =>
                {
                    b.HasOne("backend.Models.Categoria", "Categoria")
                        .WithMany("Productos")
                        .HasForeignKey("IdCategoria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("backend.Models.ProductoAtributo", b =>
                {
                    b.HasOne("backend.Models.Atributo", "Atributo")
                        .WithMany("ProductoAtributos")
                        .HasForeignKey("IdAtributo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Producto", "Producto")
                        .WithMany("Atributos")
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Atributo");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("backend.Models.ProductoSerial", b =>
                {
                    b.HasOne("backend.Models.Producto", "Producto")
                        .WithMany("Seriales")
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("backend.Models.Reparacion", b =>
                {
                    b.HasOne("backend.Models.Cliente", "Cliente")
                        .WithMany("Reparaciones")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend.Models.Usuario", "Tecnico")
                        .WithMany("Reparaciones")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Tecnico");
                });

            modelBuilder.Entity("backend.Models.ReparacionRepuesto", b =>
                {
                    b.HasOne("backend.Models.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend.Models.Reparacion", "Reparacion")
                        .WithMany("Repuestos")
                        .HasForeignKey("IdReparacion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.ProductoSerial", "Serial")
                        .WithMany()
                        .HasForeignKey("IdSerial")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Producto");

                    b.Navigation("Reparacion");

                    b.Navigation("Serial");
                });

            modelBuilder.Entity("backend.Models.AnalisisIA", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("backend.Models.Atributo", b =>
                {
                    b.Navigation("ProductoAtributos");
                });

            modelBuilder.Entity("backend.Models.Categoria", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("backend.Models.Cliente", b =>
                {
                    b.Navigation("Facturas");

                    b.Navigation("Reparaciones");
                });

            modelBuilder.Entity("backend.Models.Factura", b =>
                {
                    b.Navigation("Detalles");

                    b.Navigation("FacturaReparaciones");
                });

            modelBuilder.Entity("backend.Models.Producto", b =>
                {
                    b.Navigation("Atributos");

                    b.Navigation("Seriales");
                });

            modelBuilder.Entity("backend.Models.Reparacion", b =>
                {
                    b.Navigation("FacturaReparaciones");

                    b.Navigation("Repuestos");
                });

            modelBuilder.Entity("backend.Models.Usuario", b =>
                {
                    b.Navigation("Facturas");

                    b.Navigation("Reparaciones");
                });
#pragma warning restore 612, 618
        }
    }
}
